version: "3"

services:
  edwardker-digitaltwin:
    container_name: edwardker-chat
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    environment:
      - USER_ID=edwardker
      - ENVIRONMENT=development
      - DIGITALTWIN_APPID=digitaltwin.jimbertesting.be
    volumes:
      - ../..:/app
      - ./appdata:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log
    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
        
  debug-digitaltwin:
    container_name: debug-chat
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    environment:
      - USER_ID=debug
      - ENVIRONMENT=development
      - DIGITALTWIN_APPID=digitaltwin.jimbertesting.be
    volumes:
      - ../..:/app
      - ./appdata_debug:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log
    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
        
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    networks:
      - chatnet
    restart: always
    environment:
      - REDIS_HOSTS=local:edwardker-digitaltwin:6379
    ports:
      - "8081:8081"
    depends_on:
      - edwardker-digitaltwin

networks:
  chatnet:
    external: true
