version: "3"

services:
  jorisb-digitaltwin:
    container_name: jorisb-chat
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    environment:
      - USER_ID=jorisb
      - ENVIRONMENT=development
      - DIGITALTWIN_APPID=digitaltwin.jimbertesting.be
    volumes:
      - ../..:/app
      - ./appdata_jorisb:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log
    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
        
  jefke7-digitaltwin:
    container_name: jefke7-chat
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile
    restart: always
    environment:
      - USER_ID=jefke7
      - ENVIRONMENT=development
      - DIGITALTWIN_APPID=digitaltwin.jimbertesting.be
    volumes:
      - ../..:/app
      - ./appdata_jefke7:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log
    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
        
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    networks:
      - chatnet
    restart: always
    environment:
      - REDIS_HOSTS=local:jorisb-digitaltwin:6379,local:jefke7-digitaltwin:6379
    ports:
      - "8081:8081"
    depends_on:
      - jorisb-digitaltwin

networks:
  chatnet:
    external: true
