on:
    push:
        branches:
            - 'main'
jobs:
    merge-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: emiliopedrollo/auto-merge@v1.2.0
              with:
                  github_token: ${{ github.token }}
                  target_branch: 'development'
                  commit_message: 'auto-merge {source_ref} into {target_branch}'
