name: beta-digitaltwin

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Build the Docker image
              run: docker build . --file ./docker/prod/Dockerfile --tag registry.gitlab.com/3bot_app_jimber/digital_twin:${{ github.sha }}
            - name: Log into GitHub Container Registry
              run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login registry.gitlab.com -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            - name: Push to gitlab registry
              run: docker push registry.gitlab.com/3bot_app_jimber/digital_twin:${{ github.sha }}
            - name: Push latest to gitlab registry
              run: |
                  docker tag registry.gitlab.com/3bot_app_jimber/digital_twin:${{ github.sha }} registry.gitlab.com/3bot_app_jimber/digital_twin:latest
                  docker push registry.gitlab.com/3bot_app_jimber/digital_twin:latest
                  docker push registry.gitlab.com/3bot_app_jimber/digital_twin:${{ github.sha }}
    deploy:
        needs: [build]
        runs-on: beta
        environment:
            name: demo.freeflow
            url: https://demo.freeflow.life/
        steps:
            - name: debugging runner
              run: |
                  curl ip4.me
                  echo "-----------"
                  echo hostname
                  echo "-----------"
                  echo ip addr

            - name: Deploying on beta server
              run: |
                  docker pull registry.gitlab.com/3bot_app_jimber/digital_twin:${{ github.sha }}
                  echo "registry.gitlab.com/3bot_app_jimber/digital_twin:${{ github.sha }}" > '/etc/digitaltwin/version.txt'
                  echo Removing all existing chat containers / volumes.
                  [ -z "$(docker ps --filter "name=-chat" -q)" ] && echo "No dockers need to be deleted" || docker rm -f $(docker ps --filter "name=-chat" -q)     
                  echo Completed.
